// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilLowercase is returned when the Lowercase is nil.
	ErrNilLowercase = errors.New("input Lowercase is nil")

	// ErrLowercaseUsernameLowercaseValidation is the error returned when the field is not all lowercase.
	ErrLowercaseUsernameLowercaseValidation = govaliderrors.ValidationError{Reason: "field Username must be lowercase", Path: "Lowercase.Username", Type: "lowercase"}
)

func ValidateLowercase(t *Lowercase) error {
	if t == nil {
		return ErrNilLowercase
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsLowercase(t.Username) {
		err := ErrLowercaseUsernameLowercaseValidation
		err.Value = t.Username
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Lowercase)(nil)

func (t *Lowercase) Validate() error {
	return ValidateLowercase(t)
}
