// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	// Local package import
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// AlphaInitializer implements ValidatorInitializer for the alpha validator.
type AlphaInitializer struct{}

// Marker returns the marker identifier for the alpha validator.
func (a AlphaInitializer) Marker() string {
	return markers.GoValidMarkerAlpha
}

// Init initializes the alpha validator factory.
func (a AlphaInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateAlpha
}
