// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// CelInitializer implements ValidatorInitializer for the cel validator.
type CelInitializer struct{}

// Marker returns the marker identifier for the cel validator.
func (c CelInitializer) Marker() string {
	return markers.GoValidMarkerCel
}

// Init initializes the cel validator factory.
func (c CelInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateCEL
}
