// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// ContainsanyInitializer implements ValidatorInitializer for the containsany validator.
type ContainsanyInitializer struct{}

// Marker returns the marker identifier for the containsany validator.
func (c ContainsanyInitializer) Marker() string {
	return markers.GoValidMarkerContainsany
}

// Init initializes the containsany validator factory.
func (c ContainsanyInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateContainsany
}
