// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// DateInitializer implements ValidatorInitializer for the date validator.
type DateInitializer struct{}

// Marker returns the marker identifier for the date validator.
func (d DateInitializer) Marker() string {
	return markers.GoValidMarkerDate
}

// Init initializes the date validator factory.
func (d DateInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateDate
}
