// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// ExcludesallInitializer implements ValidatorInitializer for the excludesall validator.
type ExcludesallInitializer struct{}

// Marker returns the marker identifier for the excludesall validator.
func (e ExcludesallInitializer) Marker() string {
	return markers.GoValidMarkerExcludesall
}

// Init initializes the excludesall validator factory.
func (e ExcludesallInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludesall
}
