// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Excluded_ifInitializer implements ValidatorInitializer for the excluded_if validator.
type Excluded_ifInitializer struct{}

// Marker returns the marker identifier for the excluded_if validator.
func (e Excluded_ifInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_if
}

// Init initializes the excluded_if validator factory.
func (e Excluded_ifInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedIf
}
