// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Excluded_with_allInitializer implements ValidatorInitializer for the excluded_with_all validator.
type Excluded_with_allInitializer struct{}

// Marker returns the marker identifier for the excluded_with_all validator.
func (e Excluded_with_allInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_with_all
}

// Init initializes the excluded_with_all validator factory.
func (e Excluded_with_allInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedWithAll
}
