// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// ExcludesInitializer implements ValidatorInitializer for the excludes validator.
type ExcludesInitializer struct{}

// Marker returns the marker identifier for the excludes validator.
func (e ExcludesInitializer) Marker() string {
	return markers.GoValidMarkerExcludes
}

// Init initializes the excludes validator factory.
func (e ExcludesInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludes
}
