// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// GtInitializer implements ValidatorInitializer for the gt validator.
type GtInitializer struct{}

// Marker returns the marker identifier for the gt validator.
func (g GtInitializer) Marker() string {
	return markers.GoValidMarkerGt
}

// Init initializes the gt validator factory.
func (g GtInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateGT
}
