// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// GteInitializer implements ValidatorInitializer for the gte validator.
type GteInitializer struct{}

// Marker returns the marker identifier for the gte validator.
func (g GteInitializer) Marker() string {
	return markers.GoValidMarkerGte
}

// Init initializes the gte validator factory.
func (g GteInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateGTE
}
