// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Ipv4Initializer implements ValidatorInitializer for the ipv4 validator.
type Ipv4Initializer struct{}

// Marker returns the marker identifier for the ipv4 validator.
func (i Ipv4Initializer) Marker() string {
	return markers.GoValidMarkerIpv4
}

// Init initializes the ipv4 validator factory.
func (i Ipv4Initializer) Init() registry.ValidatorFactory {
	return rules.ValidateIpv4
}
