// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// IsdefaultInitializer implements ValidatorInitializer for the isdefault validator.
type IsdefaultInitializer struct{}

// Marker returns the marker identifier for the isdefault validator.
func (i IsdefaultInitializer) Marker() string {
	return markers.GoValidMarkerIsdefault
}

// Init initializes the isdefault validator factory.
func (i IsdefaultInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateIsdefault
}
