// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// LatitudeInitializer implements ValidatorInitializer for the latitude validator.
type LatitudeInitializer struct{}

// Marker returns the marker identifier for the latitude validator.
func (l LatitudeInitializer) Marker() string {
	return markers.GoValidMarkerLatitude
}

// Init initializes the latitude validator factory.
func (l LatitudeInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLatitude
}
