// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// LengthInitializer implements ValidatorInitializer for the length validator.
type LengthInitializer struct{}

// Marker returns the marker identifier for the length validator.
func (l LengthInitializer) Marker() string {
	return markers.GoValidMarkerLength
}

// Init initializes the length validator factory.
func (l LengthInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLength
}
