// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// LteInitializer implements ValidatorInitializer for the lte validator.
type LteInitializer struct{}

// Marker returns the marker identifier for the lte validator.
func (l LteInitializer) Marker() string {
	return markers.GoValidMarkerLte
}

// Init initializes the lte validator factory.
func (l LteInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLTE
}
