// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// MaxitemsInitializer implements ValidatorInitializer for the maxitems validator.
type MaxitemsInitializer struct{}

// Marker returns the marker identifier for the maxitems validator.
func (m MaxitemsInitializer) Marker() string {
	return markers.GoValidMarkerMaxitems
}

// Init initializes the maxitems validator factory.
func (m MaxitemsInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMaxItems
}
