// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// MaxlengthInitializer implements ValidatorInitializer for the maxlength validator.
type MaxlengthInitializer struct{}

// Marker returns the marker identifier for the maxlength validator.
func (m MaxlengthInitializer) Marker() string {
	return markers.GoValidMarkerMaxlength
}

// Init initializes the maxlength validator factory.
func (m MaxlengthInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMaxLength
}
