// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// MindurationInitializer implements ValidatorInitializer for the minduration validator.
type MindurationInitializer struct{}

// Marker returns the marker identifier for the minduration validator.
func (m MindurationInitializer) Marker() string {
	return markers.GoValidMarkerMinduration
}

// Init initializes the minduration validator factory.
func (m MindurationInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMinduration
}
