// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// MinitemsInitializer implements ValidatorInitializer for the minitems validator.
type MinitemsInitializer struct{}

// Marker returns the marker identifier for the minitems validator.
func (m MinitemsInitializer) Marker() string {
	return markers.GoValidMarkerMinitems
}

// Init initializes the minitems validator factory.
func (m MinitemsInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMinItems
}
