// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// MinlengthInitializer implements ValidatorInitializer for the minlength validator.
type MinlengthInitializer struct{}

// Marker returns the marker identifier for the minlength validator.
func (m MinlengthInitializer) Marker() string {
	return markers.GoValidMarkerMinlength
}

// Init initializes the minlength validator factory.
func (m MinlengthInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMinLength
}
