// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// NumericInitializer implements ValidatorInitializer for the numeric validator.
type NumericInitializer struct{}

// Marker returns the marker identifier for the numeric validator.
func (n NumericInitializer) Marker() string {
	return markers.GoValidMarkerNumeric
}

// Init initializes the numeric validator factory.
func (n NumericInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateNumeric
}
