// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// OneofInitializer implements ValidatorInitializer for the oneof validator.
type OneofInitializer struct{}

// Marker returns the marker identifier for the oneof validator.
func (o OneofInitializer) Marker() string {
	return markers.GoValidMarkerOneof
}

// Init initializes the oneof validator factory.
func (o OneofInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateOneof
}
