// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Required_withoutInitializer implements ValidatorInitializer for the required_without validator.
type Required_withoutInitializer struct{}

// Marker returns the marker identifier for the required_without validator.
func (r Required_withoutInitializer) Marker() string {
	return markers.GoValidMarkerRequired_without
}

// Init initializes the required_without validator factory.
func (r Required_withoutInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequiredWithout
}
