// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Required_withInitializer implements ValidatorInitializer for the required_with validator.
type Required_withInitializer struct{}

// Marker returns the marker identifier for the required_with validator.
func (r Required_withInitializer) Marker() string {
	return markers.GoValidMarkerRequired_with
}

// Init initializes the required_with validator factory.
func (r Required_withInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequiredWith
}
