// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// Required_unlessInitializer implements ValidatorInitializer for the required_unless validator.
type Required_unlessInitializer struct{}

// Marker returns the marker identifier for the required_unless validator.
func (r Required_unlessInitializer) Marker() string {
	return markers.GoValidMarkerRequired_unless
}

// Init initializes the required_unless validator factory.
func (r Required_unlessInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequiredUnless
}
