// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/markers"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/registry"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/internal/validator/rules"
)

// UuidInitializer implements ValidatorInitializer for the uuid validator.
type UuidInitializer struct{}

// Marker returns the marker identifier for the uuid validator.
func (u UuidInitializer) Marker() string {
	return markers.GoValidMarkerUuid
}

// Init initializes the uuid validator factory.
func (u UuidInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateUUID
}
